version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - '8081:80'
    volumes:
      - ./:/app
      - .nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    volumes:
      - ./:/app
  db:
    image: mysql:5.7
    restart: always
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: polkaworld
      MYSQL_USER: polkaworld
      MYSQL_PASSWORD: '*4u6gz{X)9)'
      MYSQL_ROOT_PASSWORD: ';DWM6j6{3/8R*kUVTw'
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    external:
      name: polkaworld_mysql
